export default {
  GET_BANNER: "@messaging/GET_BANNER",
  GET_BANNER_SUCCESS: "@messaging/GET_BANNER_SUCCESS",
  GET_BANNER_ERROR: "@messaging/GET_BANNER_ERROR",

  ADD_BANNER: "@messaging/ADD_BANNER",
  ADD_BANNER_SUCCESS: "@messaging/ADD_BANNER_SUCCESS",
  ADD_BANNER_ERROR: "@messaging/ADD_BANNER_ERROR",

  REMOVE_BANNER: "@messaging/REMOVE_BANNER",
  REMOVE_BANNER_SUCCESS: "@messaging/REMOVE_BANNER_SUCCESS",
  REMOVE_BANNER_ERROR: "@messaging/REMOVE_BANNER_ERROR",

  CLEAN_CACHE_ADMIN: "@messaging/CLEAN_CACHE",
};
