export default {
  GET_PRODUCTS: "@messaging/GET_PRODUCTS",
  GET_PRODUCTS_SUCCESS: "@messaging/GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_ERROR: "@messaging/GET_PRODUCTS_ERROR",

  GET_PRODUCT_DETAIL: "@messaging/GET_PRODUCT_DETAIL",
  GET_PRODUCT_DETAIL_SUCCESS: "@messaging/GET_PRODUCT_DETAIL_SUCCESS",
  GET_PRODUCT_DETAIL_ERROR: "@messaging/GET_PRODUCT_DETAIL_ERROR",

  CREATE_PRODUCT: "@messaging/CREATE_PRODUCT",
  CREATE_PRODUCT_SUCCESS: "@messaging/CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_ERROR: "@messaging/CREATE_PRODUCT_ERROR",

  EDIT_PRODUCT: "@messaging/EDIT_PRODUCT",
  EDIT_PRODUCT_SUCCESS: "@messaging/EDIT_PRODUCT_SUCCESS",
  EDIT_PRODUCT_ERROR: "@messaging/EDIT_PRODUCT_ERROR",

  DELETE_PRODUCT: "@messaging/DELETE_PRODUCT",
  DELETE_PRODUCT_SUCCESS: "@messaging/DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_ERROR: "@messaging/DELETE_PRODUCT_ERROR",

  SEARCH_BAR_PRODUCT: "@messaging/SEARCH_BAR_PRODUCT",
  SEARCH_BAR_PRODUCT_SUCCESS: "@messaging/SEARCH_BAR_PRODUCT_SUCCESS",
  SEARCH_BAR_PRODUCT_ERROR: "@messaging/SEARCH_BAR_PRODUCT_ERROR",

  CLEAN_CACHE_PRODUCTS: "@messaging/CLEAN_CACHE",
};
