export default {
  GET_PRODUCTS: "@messaging/GET_PRODUCTS",
  GET_PRODUCTS_SUCCESS: "@messaging/GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_ERROR: "@messaging/GET_PRODUCTS_ERROR",

  CREATE_PRODUCT: "@messaging/CREATE_PRODUCT",
  CREATE_PRODUCT_SUCCESS: "@messaging/CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_ERROR: "@messaging/CREATE_PRODUCT_ERROR",

  DELETE_PRODUCT: "@messaging/DELETE_PRODUCT",
  DELETE_PRODUCT_SUCCESS: "@messaging/DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_ERROR: "@messaging/DELETE_PRODUCT_ERROR",

  CLEAN_CACHE_PRODUCTS: "@messaging/CLEAN_CACHE",
};
