export const ITEMS = [
  {
    id: 1,
    img: "https://www.milenioartefatos.com.br/wp-content/uploads/2022/06/Couro-Malibu-600x600.webp",
    titulo: "Courvin Diamante",
    precoEmCentavos: 2550,
    tags: ["tecidos"],
  },
  {
    id: 2,
    img: "https://www.milenioartefatos.com.br/wp-content/uploads/2022/06/Linho-Collins-Milenio-Artefatos--600x600.webp",
    titulo: "Matelassê para Bolsas",
    precoEmCentavos: 2550,
    tags: ["tecidos"],
  },
  {
    id: 3,
    img: "https://www.milenioartefatos.com.br/wp-content/uploads/2022/06/Courvin-Diamante-600x600.webp",
    titulo: "Tecido Melange",
    precoEmCentavos: 2550,
    tags: ["tecidos"],
  },
  {
    id: 4,
    img: "https://www.milenioartefatos.com.br/wp-content/uploads/2022/06/Melange-600-MIlenio-Artefatos-600x600.webp",
    titulo: "Couro Malibu",
    precoEmCentavos: 2550,
    tags: ["tecidos"],
  },
  {
    id: 5,
    img: "https://www.milenioartefatos.com.br/wp-content/uploads/2020/10/Adesivo-Automotivo-Alltak-Carbon-4D-Preto.jpg",
    titulo: "Adesivo Automotivo Alltak Carbon 4D Vermelho",
    precoEmCentavos: 2550,
    tags: ["automotivos"],
  },
  {
    id: 6,
    img: "https://www.milenioartefatos.com.br/wp-content/uploads/2020/10/Adesivo-Automotivo-Alltak-Carbon-4D-vermelho.jpg",
    titulo: "Adesivo Automotivo Alltak Carbon 4D Preto",
    precoEmCentavos: 2550,
    tags: ["automotivos"],
  },
  {
    id: 7,
    img: "https://www.milenioartefatos.com.br/wp-content/uploads/2020/10/980484-MLA26901586588_022018-F.jpg",
    titulo: "Adesivo Automotivo Alltak Kamo Urban City Metálico",
    precoEmCentavos: 2550,
    tags: ["automotivos"],
  },
  {
    id: 8,
    img: "https://www.milenioartefatos.com.br/wp-content/uploads/2020/10/ALLTAK-KAMO-URBAN-CITY.jpeg",
    titulo: "Adesivo Automotivo Alltak Kamo Urban Floresta",
    precoEmCentavos: 2550,
    tags: ["automotivos"],
  },
];
